<?php

D: $x=1;

try {
    f();
} catch (\Exception $x) { }

U: $x;